"""esquema inicial FINART

Revision ID: ba72a5e5c3ea
Revises: 
Create Date: 2026-07-28 11:02:45.173482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba72a5e5c3ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('ing_brutos', sa.String(length=30), nullable=True),
    sa.Column('inicio_actividades', sa.String(length=30), nullable=True),
    sa.Column('cond_iva', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('horario', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('recibo_prefijo', sa.String(length=8), nullable=True),
    sa.Column('recibo_proximo', sa.Integer(), nullable=True),
    sa.Column('liquidacion_prefijo', sa.String(length=8), nullable=True),
    sa.Column('liquidacion_proximo', sa.Integer(), nullable=True),
    sa.Column('pagare_meses', sa.Integer(), nullable=True),
    sa.Column('pagare_lugar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gas_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta', sa.String(length=30), nullable=False),
    sa.Column('titular', sa.String(length=160), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('contrato_vigente', sa.Boolean(), nullable=True),
    sa.Column('tiene_deuda', sa.Boolean(), nullable=True),
    sa.Column('deuda_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ultimo_vencimiento', sa.Date(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta')
    )
    op.create_table('indices_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('fuente', sa.String(length=40), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'periodo', name='uq_indice_periodo')
    )
    op.create_table('pagares_manuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('lugar', sa.String(length=120), nullable=True),
    sa.Column('beneficiario', sa.String(length=160), nullable=True),
    sa.Column('deudor', sa.String(length=160), nullable=False),
    sa.Column('deudor_dni', sa.String(length=20), nullable=True),
    sa.Column('deudor_domicilio', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('primer_venc', sa.Date(), nullable=True),
    sa.Column('cada_dias', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('domicilio', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cond_iva', sa.String(length=40), nullable=True),
    sa.Column('es_propietario', sa.Boolean(), nullable=True),
    sa.Column('es_inquilino', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recibos_manuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cliente', sa.String(length=160), nullable=False),
    sa.Column('cliente_dni', sa.String(length=20), nullable=True),
    sa.Column('cliente_domicilio', sa.String(length=200), nullable=True),
    sa.Column('concepto_general', sa.String(length=200), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('forma_pago', sa.String(length=60), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inmuebles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('barrio', sa.String(length=120), nullable=True),
    sa.Column('dormitorios', sa.Integer(), nullable=True),
    sa.Column('banos', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('precio_referencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comision_pct', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cuenta_gas', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('propietario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('duracion_meses', sa.Integer(), nullable=True),
    sa.Column('precio_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_actual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('dia_vencimiento', sa.Integer(), nullable=True),
    sa.Column('mora_diaria_pct', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('comision_pct', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('metodo_ajuste', sa.String(length=20), nullable=True),
    sa.Column('indice_tipo', sa.String(length=20), nullable=True),
    sa.Column('ajuste_cada_meses', sa.Integer(), nullable=True),
    sa.Column('porcentaje_ajuste', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('aumento_pospuesto', sa.Date(), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('documento_html', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmuebles.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['propietario_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_vigencia', sa.Date(), nullable=False),
    sa.Column('precio_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('precio_nuevo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('indice_tipo', sa.String(length=20), nullable=True),
    sa.Column('indice_inicio', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('indice_fin', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_colocadores',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('contrato_id', 'persona_id')
    )
    op.create_table('contrato_colocatarios',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('contrato_id', 'persona_id')
    )
    op.create_table('fiadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('domicilio', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('solvencia', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('periodo_mes', sa.Integer(), nullable=True),
    sa.Column('periodo_anio', sa.Integer(), nullable=True),
    sa.Column('propietario_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('total_ingresos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_comision', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_neto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['propietario_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('periodo_mes', sa.Integer(), nullable=True),
    sa.Column('periodo_anio', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('precio_alquiler', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mora', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pagado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('forma_pago', sa.String(length=60), nullable=True),
    sa.Column('pagado_al_propietario', sa.Date(), nullable=True),
    sa.Column('recibo_numero', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos_extra')
    op.drop_table('pagos')
    op.drop_table('liquidaciones')
    op.drop_table('fiadores')
    op.drop_table('contrato_colocatarios')
    op.drop_table('contrato_colocadores')
    op.drop_table('aumentos')
    op.drop_table('contratos')
    op.drop_table('inmuebles')
    op.drop_table('usuarios')
    op.drop_table('recibos_manuales')
    op.drop_table('personas')
    op.drop_table('pagares_manuales')
    op.drop_table('indices_valores')
    op.drop_table('gas_estado')
    op.drop_table('ajustes')
    # ### end Alembic commands ###
